Repository CoreDisc/CoreDisc-BE, pull requests merged in 2025-08, with the labels that each got.

#120 Feat: 댓글 api 구현
  src/main/java/com/coredisc/application/service/comment/CommentCommandService.java
  src/main/java/com/coredisc/application/service/comment/CommentCommandServiceImpl.java
  src/main/java/com/coredisc/application/service/comment/CommentQueryService.java
  src/main/java/com/coredisc/application/service/comment/CommentQueryServiceImpl.java
  src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
  src/main/java/com/coredisc/common/converter/CommentConverter.java
  src/main/java/com/coredisc/common/exception/handler/CommentHandler.java
  src/main/java/com/coredisc/domain/Comment.java
  src/main/java/com/coredisc/domain/comment/CommentRepository.java
  src/main/java/com/coredisc/infrastructure/repository/comment/CommentRepositoryAdaptor.java
  src/main/java/com/coredisc/infrastructure/repository/comment/JpaCommentRepository.java
  src/main/java/com/coredisc/infrastructure/repository/comment/queryDsl/CommentQueryRepository.java
  src/main/java/com/coredisc/infrastructure/repository/comment/queryDsl/commentQueryRepositoryImpl.java
  src/main/java/com/coredisc/presentation/controller/CommentController.java
  src/main/java/com/coredisc/presentation/controllerdocs/CommentControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/comment/CommentRequestDTO.java
  src/main/java/com/coredisc/presentation/dto/comment/CommentResponseDTO.java
Labels: ✨ Feature

#131 Feat: 타사용자의 팔로워,팔로잉 목록 조회 API 구현
  src/main/java/com/coredisc/application/service/follow/FollowQueryService.java
  src/main/java/com/coredisc/application/service/follow/FollowQueryServiceImpl.java
  src/main/java/com/coredisc/common/converter/FollowConverter.java
  src/main/java/com/coredisc/presentation/controller/FollowController.java
  src/main/java/com/coredisc/presentation/controllerdocs/FollowControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/follow/FollowResponseDTO.java
Labels: ✨ Feature

#135 Refactor: 비밀번호 변경을 위한 사용자 검증 요청 dto 및 로직 수정
  src/main/java/com/coredisc/application/service/auth/AuthQueryServiceImpl.java
  src/main/java/com/coredisc/domain/member/MemberRepository.java
  src/main/java/com/coredisc/infrastructure/repository/member/JpaMemberRepository.java
  src/main/java/com/coredisc/infrastructure/repository/member/MemberRepositoryAdaptor.java
  src/main/java/com/coredisc/presentation/dto/auth/AuthRequestDTO.java
Labels: 🔨 Refactor

#137 Refactor: 회원가입 요청 dto 검증 어노테이션 추가
  src/main/java/com/coredisc/presentation/dto/auth/AuthRequestDTO.java
Labels: 🔨 Refactor

#141 Feat: 마이홈 - 내가 작성한 질문들 조회 API 구현
  src/main/java/com/coredisc/application/service/member/MemberQueryService.java
  src/main/java/com/coredisc/application/service/member/MemberQueryServiceImpl.java
  src/main/java/com/coredisc/infrastructure/repository/question/CustomQuestionRepository.java
  src/main/java/com/coredisc/infrastructure/repository/question/CustomQuestionRepositoryAdapter.java
  src/main/java/com/coredisc/infrastructure/repository/question/querydsl/QueryCustomQuestionRepository.java
  src/main/java/com/coredisc/infrastructure/repository/question/querydsl/QueryCustomQuestionRepositoryImpl.java
  src/main/java/com/coredisc/presentation/controller/MemberController.java
  src/main/java/com/coredisc/presentation/controllerdocs/MemberControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/member/MemberResponseDTO.java
Labels: ✨ Feature

#161 Refactor: 기본 질문 목록 선택&즐겨찾기 여부 추가
  src/main/java/com/coredisc/application/service/question/QuestionQueryServiceImpl.java
  src/main/java/com/coredisc/common/converter/QuestionConverter.java
  src/main/java/com/coredisc/domain/mapping/memberOfficialQuestion/MemberOfficialQuestionRepository.java
  src/main/java/com/coredisc/domain/officialQuestion/OfficialQuestionRepository.java
  src/main/java/com/coredisc/infrastructure/repository/question/JpaMemberOfficialQuestionRepository.java
  src/main/java/com/coredisc/infrastructure/repository/question/JpaOfficialQuestionRepository.java
  src/main/java/com/coredisc/infrastructure/repository/question/MemberOfficialQuestionRepositoryAdapter.java
  src/main/java/com/coredisc/infrastructure/repository/question/OfficialQuestionRepositoryAdapter.java
  src/main/java/com/coredisc/infrastructure/repository/question/querydsl/QueryCustomQuestionRepositoryImpl.java
  src/main/java/com/coredisc/presentation/dto/question/QuestionResponseDTO.java
Labels: 🔨 Refactor

#156 Refactor: 임시저장 알림 생성 시, 프로필 이미지 null로 반환되도록 수정
  src/main/java/com/coredisc/application/schedule/NotificationScheduler.java
  src/main/java/com/coredisc/common/converter/NotificationConverter.java
Labels: 🔨 Refactor

#174 Refactor: 게시글 조회 api 수정
  src/main/java/com/coredisc/common/converter/PostConverter.java
  src/main/java/com/coredisc/infrastructure/repository/post/queryDsl/QueryPostRepositoryImpl.java
  src/main/java/com/coredisc/presentation/dto/post/PostResponseDTO.java
Labels: 🔨 Refactor

#170 feat: 캘린더 API 2개로 분리
  src/main/java/com/coredisc/application/service/calendar/CalendarQueryService.java
  src/main/java/com/coredisc/application/service/calendar/CalendarQueryServiceImpl.java
  src/main/java/com/coredisc/common/converter/CalendarConverter.java
  src/main/java/com/coredisc/presentation/controller/CalendarController.java
  src/main/java/com/coredisc/presentation/controllerdocs/CalendarControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/calendar/CalendarResponseDTO.java
Labels: ✨ Feature, 🔨 Refactor

#175 Refactor: 기본 제공 질문 관련 수정
  src/main/java/com/coredisc/application/service/question/QuestionCommandServiceImpl.java
  src/main/java/com/coredisc/application/service/question/QuestionQueryServiceImpl.java
  src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
Labels: 🔨 Refactor

#177 Refactor: TermsType title 수정 및 응답 수정
  src/main/java/com/coredisc/common/converter/TermsConverter.java
  src/main/java/com/coredisc/domain/common/enums/TermsType.java
  src/main/java/com/coredisc/presentation/dto/terms/TermsResponseDTO.java
Labels: 🔨 Refactor

#179 Refactor: 마이홈 - 아이디/닉네임 수정 후 성공 응답 반환 코드 구분하도록 수정
  src/main/java/com/coredisc/common/apiPayload/ApiResponse.java
  src/main/java/com/coredisc/common/apiPayload/status/SuccessStatus.java
  src/main/java/com/coredisc/presentation/controller/MemberController.java
Labels: ✨ Feature, 🔨 Refactor

#180 Refactor: 게시글 조회 응답 관련 api 수정
  src/main/java/com/coredisc/common/converter/PostConverter.java
  src/main/java/com/coredisc/presentation/dto/post/PostResponseDTO.java
Labels: 🔨 Refactor

#185 Refactor: 질문 수정 어노테이션 추가
  src/main/java/com/coredisc/presentation/controller/QuestionController.java
Labels: 🔨 Refactor

#187 Refactor: 로그인 API 수정
  src/main/java/com/coredisc/application/service/auth/AuthCommandServiceImpl.java
  src/main/java/com/coredisc/domain/member/MemberRepository.java
  src/main/java/com/coredisc/infrastructure/repository/member/JpaMemberRepository.java
  src/main/java/com/coredisc/infrastructure/repository/member/MemberRepositoryAdaptor.java
Labels: 🔨 Refactor

#181 Refactor: Temp Post api 수정
  src/main/java/com/coredisc/application/service/post/PostCommandServiceImpl.java
  src/main/java/com/coredisc/common/converter/PostConverter.java
  src/main/java/com/coredisc/presentation/dto/post/PostResponseDTO.java
Labels: 🔨 Refactor

#190 Refactor: 댓글 api 관련 리팩토링
  src/main/java/com/coredisc/application/service/comment/CommentQueryServiceImpl.java
  src/main/java/com/coredisc/common/converter/CommentConverter.java
  src/main/java/com/coredisc/domain/Comment.java
  src/main/java/com/coredisc/presentation/dto/comment/CommentResponseDTO.java
Labels: 🔨 Refactor

#189 refactor: 디스크 목록 한 번에 조회하도록 수정
  src/main/java/com/coredisc/application/service/disc/DiscQueryService.java
  src/main/java/com/coredisc/application/service/disc/DiscQueryServiceImpl.java
  src/main/java/com/coredisc/common/converter/DiscConverter.java
  src/main/java/com/coredisc/domain/disc/DiscRepository.java
  src/main/java/com/coredisc/infrastructure/repository/disc/DiscRepositoryAdaptor.java
  src/main/java/com/coredisc/infrastructure/repository/disc/JpaDiscRepository.java
  src/main/java/com/coredisc/presentation/controller/DiscController.java
  src/main/java/com/coredisc/presentation/controllerdocs/DiscControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/disc/DiscResponseDTO.java
Labels: 🔨 Refactor

#198 Refactor: 댓글 관련 api 수정
  src/main/java/com/coredisc/application/service/comment/CommentCommandServiceImpl.java
  src/main/java/com/coredisc/application/service/comment/CommentQueryServiceImpl.java
  src/main/java/com/coredisc/common/converter/CommentConverter.java
  src/main/java/com/coredisc/presentation/controller/CommentController.java
  src/main/java/com/coredisc/presentation/dto/comment/CommentResponseDTO.java
Labels: 🔨 Refactor

#194 Refactor: 대댓글 알림 메시지 수정
  src/main/java/com/coredisc/application/service/comment/CommentCommandServiceImpl.java
Labels: 🔨 Refactor

#201 Refactor: id말고 officialquestion 비교하도록 수정
  src/main/java/com/coredisc/application/service/question/QuestionQueryServiceImpl.java
Labels: 🔨 Refactor

#206 Refactor: 리마인더 알림 시간 5분 단위로 설정되도록 수정
  src/main/java/com/coredisc/application/schedule/NotificationReminderScheduler.java
  src/main/java/com/coredisc/application/service/notificationReminderSetting/NotificationReminderSettingCommandServiceImpl.java
  src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
Labels: 🔨 Refactor

#208 Refactor: 마이홈 - 내가 작성한 질문 공유여부 추가
  src/main/java/com/coredisc/infrastructure/repository/question/querydsl/QueryCustomQuestionRepositoryImpl.java
  src/main/java/com/coredisc/presentation/dto/member/MemberResponseDTO.java
Labels: 🔨 Refactor

#210 Refactor: 언팔로우 시, 친한친구 상태 해제되도록 수정
  src/main/java/com/coredisc/application/service/follow/FollowCommandServiceImpl.java
Labels: 🔨 Refactor

#214 Refactor: 디스크, 리포트 api 수정
  src/main/java/com/coredisc/application/service/disc/DiscCommandServiceImpl.java
  src/main/java/com/coredisc/application/service/reportStat/ReportRawData.java
  src/main/java/com/coredisc/application/service/reportStat/ReportStatQueryService.java
  src/main/java/com/coredisc/application/service/reportStat/ReportStatQueryServiceImpl.java
  src/main/java/com/coredisc/common/converter/ReportStatConverter.java
  src/main/java/com/coredisc/domain/disc/DiscRepository.java
  src/main/java/com/coredisc/infrastructure/repository/disc/DiscRepositoryAdaptor.java
  src/main/java/com/coredisc/infrastructure/repository/disc/JpaDiscRepository.java
  src/main/java/com/coredisc/presentation/controllerdocs/ReportStatControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/reportStat/ReportStatResponseDTO.java
Labels: 🔨 Refactor

#217 Feat: 소셜로그인 계정 판별 API 구현
  src/main/java/com/coredisc/common/converter/MemberConverter.java
  src/main/java/com/coredisc/presentation/controller/MemberController.java
  src/main/java/com/coredisc/presentation/controllerdocs/MemberControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/member/MemberResponseDTO.java
Labels: ✨ Feature

#223 Refactor: 질문 조회 한국 시간대로 수정
  src/main/java/com/coredisc/application/service/question/QuestionQueryServiceImpl.java
Labels: 🔨 Refactor

#226 Refactor: 모든 질문 저장 가능으로 수정
  src/main/java/com/coredisc/application/service/question/QuestionCommandService.java
  src/main/java/com/coredisc/application/service/question/QuestionCommandServiceImpl.java
  src/main/java/com/coredisc/application/service/question/QuestionQueryServiceImpl.java
  src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
  src/main/java/com/coredisc/common/converter/QuestionConverter.java
  src/main/java/com/coredisc/domain/common/enums/QuestionScope.java
  src/main/java/com/coredisc/domain/mapping/memberOfficialQuestion/MemberOfficialQuestion.java
  src/main/java/com/coredisc/domain/mapping/memberOfficialQuestion/MemberOfficialQuestionRepository.java
  src/main/java/com/coredisc/domain/personalQuestion/PersonalQuestion.java
  src/main/java/com/coredisc/infrastructure/repository/question/JpaMemberOfficialQuestionRepository.java
  src/main/java/com/coredisc/infrastructure/repository/question/MemberOfficialQuestionRepositoryAdapter.java
  src/main/java/com/coredisc/infrastructure/repository/question/querydsl/QueryMemberOfficialQuestionRepositoryImpl.java
  src/main/java/com/coredisc/presentation/controller/QuestionController.java
  src/main/java/com/coredisc/presentation/controllerdocs/QuestionControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/question/QuestionRequestDTO.java
  src/main/java/com/coredisc/presentation/dto/question/QuestionResponseDTO.java
Labels: 🔨 Refactor
