Repository CoreDisc/CoreDisc-BE, pull requests merged in 2025-07, with the labels that each got.

#3 BaseEntity 생성
  src/main/java/com/coredisc/CorediscApplication.java
  src/main/java/com/coredisc/domain/common/BaseEntity.java
Labels: ✨ Feature

#5 Feature/#4
  src/main/java/com/coredisc/domain/Category.java
  src/main/java/com/coredisc/domain/Comment.java
  src/main/java/com/coredisc/domain/Device.java
  src/main/java/com/coredisc/domain/Follow.java
  src/main/java/com/coredisc/domain/Like.java
  src/main/java/com/coredisc/domain/Member.java
  src/main/java/com/coredisc/domain/Notification.java
  src/main/java/com/coredisc/domain/NotificationSetting.java
  src/main/java/com/coredisc/domain/NotificationType.java
  src/main/java/com/coredisc/domain/OfficialQuestion.java
  src/main/java/com/coredisc/domain/PersonalQuestion.java
  src/main/java/com/coredisc/domain/Post.java
  src/main/java/com/coredisc/domain/PostAnswer.java
  src/main/java/com/coredisc/domain/PostAnswerImage.java
  src/main/java/com/coredisc/domain/ProfileImg.java
  src/main/java/com/coredisc/domain/Terms.java
  src/main/java/com/coredisc/domain/TodayQuestion.java
  src/main/java/com/coredisc/domain/common/BaseEntity.java
  src/main/java/com/coredisc/domain/common/enums/AnswerType.java
  src/main/java/com/coredisc/domain/common/enums/PostStatus.java
  src/main/java/com/coredisc/domain/common/enums/PublicityType.java
  src/main/java/com/coredisc/domain/mapping/.gitkeep
  src/main/java/com/coredisc/infrastructure/repository/test/TestRepositoryAdaptor.java
  src/main/java/com/coredisc/presentation/controller/TestController.java
Labels: ✨ Feature

#10 Feat: 회원가입 관련 API 구현
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/com/coredisc/CorediscApplication.java
  src/main/java/com/coredisc/application/service/auth/AuthCommandService.java
  src/main/java/com/coredisc/application/service/auth/AuthCommandServiceImpl.java
  src/main/java/com/coredisc/application/service/auth/AuthQueryService.java
  src/main/java/com/coredisc/application/service/auth/AuthQueryServiceImpl.java
  src/main/java/com/coredisc/application/service/auth/MailService.java
  src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
  src/main/java/com/coredisc/common/converter/MemberConverter.java
  src/main/java/com/coredisc/common/exception/handler/AuthHandler.java
  src/main/java/com/coredisc/common/util/RedisUtil.java
  src/main/java/com/coredisc/config/AsyncConfig.java
  src/main/java/com/coredisc/config/MailConfig.java
  src/main/java/com/coredisc/config/RedisConfig.java
  src/main/java/com/coredisc/config/SecurityConfig.java
  src/main/java/com/coredisc/domain/Block.java
  src/main/java/com/coredisc/domain/Comment.java
  src/main/java/com/coredisc/domain/Device.java
  src/main/java/com/coredisc/domain/Follow.java
  src/main/java/com/coredisc/domain/Member.java
  src/main/java/com/coredisc/domain/MemberNotification.java
  src/main/java/com/coredisc/domain/NotificationSetting.java
  src/main/java/com/coredisc/domain/OfficialQuestion.java
  src/main/java/com/coredisc/domain/PersonalQuestion.java
  src/main/java/com/coredisc/domain/Post.java
  src/main/java/com/coredisc/domain/PostLike.java
  src/main/java/com/coredisc/domain/TodayQuestion.java
  src/main/java/com/coredisc/domain/common/enums/OauthType.java
  src/main/java/com/coredisc/domain/member/Member.java
  src/main/java/com/coredisc/domain/member/MemberRepository.java
  src/main/java/com/coredisc/infrastructure/repository/member/JpaMemberRepository.java
  src/main/java/com/coredisc/infrastructure/repository/member/MemberRepositoryAdaptor.java
  src/main/java/com/coredisc/presentation/controller/AuthController.java
  src/main/java/com/coredisc/presentation/controllerdocs/AuthControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/auth/AuthRequestDTO.java
  src/main/java/com/coredisc/presentation/dto/auth/AuthResponseDTO.java
  src/main/resources/application.yml
Labels: ✨ Feature

#17 Feature/#13
  src/main/java/com/coredisc/domain/Comment.java
  src/main/java/com/coredisc/domain/Post.java
  src/main/java/com/coredisc/domain/PostAnswer.java
  src/main/java/com/coredisc/domain/PostAnswerImage.java
  src/main/java/com/coredisc/domain/PostLike.java
  src/main/java/com/coredisc/domain/TodayQuestion.java
Labels: ✨ Feature

#22 Feat: 팔로우 관련 API 구현
  src/main/java/com/coredisc/application/service/follow/FollowCommandService.java
  src/main/java/com/coredisc/application/service/follow/FollowCommandServiceImpl.java
  src/main/java/com/coredisc/application/service/follow/FollowQueryService.java
  src/main/java/com/coredisc/application/service/follow/FollowQueryServiceImpl.java
  src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
  src/main/java/com/coredisc/common/converter/FollowConverter.java
  src/main/java/com/coredisc/common/exception/handler/FollowHandler.java
  src/main/java/com/coredisc/common/exception/handler/MemberHandler.java
  src/main/java/com/coredisc/domain/follow/Follow.java
  src/main/java/com/coredisc/domain/follow/FollowRepository.java
  src/main/java/com/coredisc/domain/member/Member.java
  src/main/java/com/coredisc/domain/member/MemberRepository.java
  src/main/java/com/coredisc/infrastructure/repository/follow/FollowRepositoryAdaptor.java
  src/main/java/com/coredisc/infrastructure/repository/follow/JpaFollowRepository.java
  src/main/java/com/coredisc/infrastructure/repository/member/MemberRepositoryAdaptor.java
  src/main/java/com/coredisc/presentation/controller/FollowController.java
  src/main/java/com/coredisc/presentation/controllerdocs/FollowControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/follow/FollowResponseDTO.java
Labels: ✨ Feature

#21 커스텀 질문 저장(생성) API 구현
  src/main/java/com/coredisc/application/service/question/QuestionCommandService.java
  src/main/java/com/coredisc/application/service/question/QuestionCommandServiceImpl.java
  src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
  src/main/java/com/coredisc/common/converter/QuestionCategoryConverter.java
  src/main/java/com/coredisc/common/converter/QuestionConverter.java
  src/main/java/com/coredisc/common/exception/handler/QuestionHandler.java
  src/main/java/com/coredisc/domain/OfficialQuestion.java
  src/main/java/com/coredisc/domain/TodayQuestion.java
  src/main/java/com/coredisc/domain/category/Category.java
  src/main/java/com/coredisc/domain/category/CategoryRepository.java
  src/main/java/com/coredisc/domain/mapping/questionCategory/QuestionCategory.java
  src/main/java/com/coredisc/domain/mapping/questionCategory/QuestionCategoryRepository.java
  src/main/java/com/coredisc/domain/personalQuestion/PersonalQuestion.java
  src/main/java/com/coredisc/domain/personalQuestion/PersonalQuestionRepository.java
  src/main/java/com/coredisc/infrastructure/repository/category/CategoryRepositoryAdaptor.java
  src/main/java/com/coredisc/infrastructure/repository/category/JpaCategoryRepository.java
  src/main/java/com/coredisc/infrastructure/repository/question/JpaPersonalQuestionRepository.java
  src/main/java/com/coredisc/infrastructure/repository/question/PersonalQuestionRepositoryAdapter.java
  src/main/java/com/coredisc/infrastructure/repository/questionCategory/JpaQuestionCategoryRepository.java
  src/main/java/com/coredisc/infrastructure/repository/questionCategory/QuestionCategoryRepositoryAdapter.java
  src/main/java/com/coredisc/presentation/controller/QuestionController.java
  src/main/java/com/coredisc/presentation/controllerdocs/QuestionControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/question/QuestionRequestDTO.java
  src/main/java/com/coredisc/presentation/dto/question/QuestionResponseDTO.java
Labels: ✨ Feature

#36 Feat: 사용자가 작성한 커스텀 질문 공유하기 API 구현
  src/main/java/com/coredisc/application/service/question/QuestionCommandService.java
  src/main/java/com/coredisc/application/service/question/QuestionCommandServiceImpl.java
  src/main/java/com/coredisc/common/converter/QuestionCategoryConverter.java
  src/main/java/com/coredisc/common/converter/QuestionConverter.java
  src/main/java/com/coredisc/domain/TodayQuestion.java
  src/main/java/com/coredisc/domain/mapping/questionCategory/QuestionCategory.java
  src/main/java/com/coredisc/domain/officialQuestion/OfficialQuestion.java
  src/main/java/com/coredisc/domain/officialQuestion/OfficialQuestionRepository.java
  src/main/java/com/coredisc/infrastructure/repository/question/JpaOfficialQuestionRepository.java
  src/main/java/com/coredisc/infrastructure/repository/question/OfficialQuestionRepositoryAdapter.java
  src/main/java/com/coredisc/presentation/controller/QuestionController.java
  src/main/java/com/coredisc/presentation/controllerdocs/QuestionControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/question/QuestionRequestDTO.java
  src/main/java/com/coredisc/presentation/dto/question/QuestionResponseDTO.java
Labels: ✨ Feature

#32 Feat: 사용자별 월간 세부 통계 API 구현
  src/main/java/com/coredisc/application/service/report/ReportRawData.java
  src/main/java/com/coredisc/application/service/report/ReportStatQueryService.java
  src/main/java/com/coredisc/application/service/report/ReportStatQueryServiceImpl.java
  src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
  src/main/java/com/coredisc/common/converter/ReportStatConverter.java
  src/main/java/com/coredisc/common/exception/handler/ReportStatsHandler.java
  src/main/java/com/coredisc/common/util/DateUtil.java
  src/main/java/com/coredisc/domain/common/enums/TimeZoneType.java
  src/main/java/com/coredisc/domain/stats/DailyAnswerHourStat.java
  src/main/java/com/coredisc/domain/stats/DailyRandomQuestionStat.java
  src/main/java/com/coredisc/domain/stats/MonthlyFixedQuestionStat.java
  src/main/java/com/coredisc/domain/stats/MonthlySelectionDiaryStat.java
  src/main/java/com/coredisc/infrastructure/repository/stats/DailyAnswerHourStatRepository.java
  src/main/java/com/coredisc/infrastructure/repository/stats/DailyRandomQuestionStatRepository.java
  src/main/java/com/coredisc/infrastructure/repository/stats/MonthlyFixedQuestionStatRepository.java
  src/main/java/com/coredisc/infrastructure/repository/stats/MonthlySelectionDiaryStatRepository.java
  src/main/java/com/coredisc/presentation/controller/ReportStatController.java
  src/main/java/com/coredisc/presentation/controllerdocs/ReportStatControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/report/ReportRequestDTO.java
  src/main/java/com/coredisc/presentation/dto/report/ReportResponseDTO.java
Labels: ✨ Feature

#39 Feat: 닉네임&아이디 변경 API 구현
  src/main/java/com/coredisc/application/service/member/MemberCommandService.java
  src/main/java/com/coredisc/application/service/member/MemberCommandServiceImpl.java
  src/main/java/com/coredisc/domain/member/Member.java
  src/main/java/com/coredisc/presentation/controller/MemberController.java
  src/main/java/com/coredisc/presentation/controllerdocs/MemberControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/auth/AuthRequestDTO.java
  src/main/java/com/coredisc/presentation/dto/member/MemberRequestDTO.java
Labels: ✨ Feature

#35 Feat: 게시글 ,답변 Create api 작성
  .gitignore
  src/main/java/com/coredisc/application/service/member/MemberQueryServiceImpl.java
  src/main/java/com/coredisc/application/service/post/PostCommandService.java
  src/main/java/com/coredisc/application/service/post/PostCommandServiceImpl.java
  src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
  src/main/java/com/coredisc/common/converter/MemberConverter.java
  src/main/java/com/coredisc/common/converter/PostConverter.java
  src/main/java/com/coredisc/common/exception/handler/PostHandler.java
  src/main/java/com/coredisc/common/util/FileUtil.java
  src/main/java/com/coredisc/config/FileStorageProperties.java
  src/main/java/com/coredisc/domain/Comment.java
  src/main/java/com/coredisc/domain/TodayQuestion.java
  src/main/java/com/coredisc/domain/common/BaseEntity.java
  src/main/java/com/coredisc/domain/member/Member.java
  src/main/java/com/coredisc/domain/post/Post.java
  src/main/java/com/coredisc/domain/post/PostAnswer.java
  src/main/java/com/coredisc/domain/post/PostAnswerImage.java
  src/main/java/com/coredisc/domain/post/PostLike.java
  src/main/java/com/coredisc/domain/post/PostRepository.java
  src/main/java/com/coredisc/domain/postAnswer/PostAnswerRepository.java
  src/main/java/com/coredisc/domain/postAnswerImage/PostAnswerImage.java
  src/main/java/com/coredisc/domain/postAnswerImage/PostAnswerImageRepository.java
  src/main/java/com/coredisc/infrastructure/file/FileInfo.java
  src/main/java/com/coredisc/infrastructure/file/FileStore.java
  src/main/java/com/coredisc/infrastructure/file/LocalFileStore.java
  src/main/java/com/coredisc/infrastructure/repository/answer/JpaPostAnswerRepository.java
  src/main/java/com/coredisc/infrastructure/repository/answer/PostAnswerRepositoryAdaptor.java
  src/main/java/com/coredisc/infrastructure/repository/post/JpaPostRepository.java
  src/main/java/com/coredisc/infrastructure/repository/post/PostRepositoryAdaptor.java
  src/main/java/com/coredisc/infrastructure/repository/postAnswerImage/JpaPostAnswerImageRepository.java
  src/main/java/com/coredisc/infrastructure/repository/postAnswerImage/PostAnswerImageRepositoryAdaptor.java
  src/main/java/com/coredisc/infrastructure/repository/postAnswerImage/queryDsl/QueryPostAnswerImageRepository.java
  src/main/java/com/coredisc/infrastructure/repository/postAnswerImage/queryDsl/QueryPostAnswerImageRepositoryImpl.java
  src/main/java/com/coredisc/infrastructure/repository/question/TodayQuestionRepository.java
  src/main/java/com/coredisc/presentation/controller/FileController.java
  src/main/java/com/coredisc/presentation/controller/PostController.java
  src/main/java/com/coredisc/presentation/controllerdocs/PostControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/post/PostRequestDTO.java
  src/main/java/com/coredisc/presentation/dto/post/PostResponseDTO.java
Labels: ✨ Feature

#41 Feat: ReportStat 구조 리팩토링 및 Disc API 구현
  src/main/java/com/coredisc/application/service/disc/DiscCommandService.java
  src/main/java/com/coredisc/application/service/disc/DiscCommandServiceImpl.java
  src/main/java/com/coredisc/application/service/disc/DiscQueryService.java
  src/main/java/com/coredisc/application/service/disc/DiscQueryServiceImpl.java
  src/main/java/com/coredisc/application/service/member/MemberQueryServiceImpl.java
  src/main/java/com/coredisc/application/service/reportStat/ReportRawData.java
  src/main/java/com/coredisc/application/service/reportStat/ReportStatQueryService.java
  src/main/java/com/coredisc/application/service/reportStat/ReportStatQueryServiceImpl.java
  src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
  src/main/java/com/coredisc/common/converter/DiscConverter.java
  src/main/java/com/coredisc/common/converter/ReportStatConverter.java
  src/main/java/com/coredisc/common/exception/handler/DiscHandler.java
  src/main/java/com/coredisc/common/exception/handler/ReportStatHandler.java
  src/main/java/com/coredisc/domain/common/enums/DiscCoverColor.java
  src/main/java/com/coredisc/domain/disc/Disc.java
  src/main/java/com/coredisc/domain/disc/DiscRepository.java
  src/main/java/com/coredisc/domain/member/Member.java
  src/main/java/com/coredisc/domain/monthlyReport/MonthlyReport.java
  src/main/java/com/coredisc/domain/monthlyReport/MonthlyReportRepository.java
  src/main/java/com/coredisc/domain/reportStats/DailyAnswerHourStat.java
  src/main/java/com/coredisc/domain/reportStats/DailyRandomQuestionStat.java
  src/main/java/com/coredisc/domain/reportStats/MonthlyFixedQuestionStat.java
  src/main/java/com/coredisc/domain/reportStats/MonthlySelectionDiaryStat.java
  src/main/java/com/coredisc/infrastructure/repository/disc/DiscRepositoryAdaptor.java
  src/main/java/com/coredisc/infrastructure/repository/disc/JpaDiscRepository.java
  src/main/java/com/coredisc/infrastructure/repository/monthlyReport/JpaMonthlyReportRepository.java
  src/main/java/com/coredisc/infrastructure/repository/monthlyReport/MonthlyReportRepositoryAdaptor.java
  src/main/java/com/coredisc/infrastructure/repository/reportStat/DailyAnswerHourStatRepository.java
  src/main/java/com/coredisc/infrastructure/repository/reportStat/DailyRandomQuestionStatRepository.java
  src/main/java/com/coredisc/infrastructure/repository/reportStat/MonthlyFixedQuestionStatRepository.java
  src/main/java/com/coredisc/infrastructure/repository/reportStat/MonthlySelectionDiaryStatRepository.java
  src/main/java/com/coredisc/presentation/controller/DiscController.java
  src/main/java/com/coredisc/presentation/controller/ReportStatController.java
  src/main/java/com/coredisc/presentation/controllerdocs/DiscControllerDocs.java
  src/main/java/com/coredisc/presentation/controllerdocs/ReportStatControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/disc/DiscRequestDTO.java
  src/main/java/com/coredisc/presentation/dto/disc/DiscResponseDTO.java
  src/main/java/com/coredisc/presentation/dto/report/ReportRequestDTO.java
  src/main/java/com/coredisc/presentation/dto/reportStat/ReportStatRequestDTO.java
  src/main/java/com/coredisc/presentation/dto/reportStat/ReportStatResponseDTO.java
Labels: ✨ Feature, 🔨 Refactor

#46 Fix: 불필요한 import문 삭제
  src/main/java/com/coredisc/application/service/member/MemberQueryServiceImpl.java
Labels: 🐞 BugFix

#59 feat: 선택한 고정&랜덤 질문 조회 API 구현
  src/main/java/com/coredisc/application/service/question/QuestionQueryService.java
  src/main/java/com/coredisc/application/service/question/QuestionQueryServiceImpl.java
  src/main/java/com/coredisc/common/converter/QuestionConverter.java
  src/main/java/com/coredisc/domain/todayQuestion/TodayQuestion.java
  src/main/java/com/coredisc/presentation/controller/QuestionController.java
  src/main/java/com/coredisc/presentation/controllerdocs/QuestionControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/question/QuestionResponseDTO.java
Labels: ✨ Feature

#68 Ci: ci/cd 파이프라인 구축
  .github/workflows/dev_deploy.yml
  Dockerfile
Labels: ✨ Feature, 👷Ci

#69 Ci: tag 이름에 latest 명시
  .github/workflows/dev_deploy.yml
Labels: 👷Ci

#70 Feat: docker 워크플로우 수정
  .github/workflows/dev_deploy.yml
Labels: ✨ Feature, 👷Ci

#72 Docs: 질문 조회 관련 API 수정중 표시 추가
  src/main/java/com/coredisc/presentation/controllerdocs/CategoryControllerDocs.java
  src/main/java/com/coredisc/presentation/controllerdocs/QuestionControllerDocs.java
Labels: 📃 Docs

#66 Feat: 캘린더 API 구현
  src/main/java/com/coredisc/application/service/calendar/CalendarQueryService.java
  src/main/java/com/coredisc/application/service/calendar/CalendarQueryServiceImpl.java
  src/main/java/com/coredisc/common/converter/CalendarConverter.java
  src/main/java/com/coredisc/common/converter/ReportStatConverter.java
  src/main/java/com/coredisc/domain/post/PostRepository.java
  src/main/java/com/coredisc/infrastructure/repository/post/PostRepositoryAdaptor.java
  src/main/java/com/coredisc/infrastructure/repository/post/queryDsl/QueryPostRepository.java
  src/main/java/com/coredisc/infrastructure/repository/post/queryDsl/QueryPostRepositoryImpl.java
  src/main/java/com/coredisc/presentation/controller/CalendarController.java
  src/main/java/com/coredisc/presentation/controllerdocs/CalendarControllerDocs.java
  src/main/java/com/coredisc/presentation/controllerdocs/DiscControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/calendar/CalendarPostDTO.java
  src/main/java/com/coredisc/presentation/dto/calendar/CalendarResponseDTO.java
  src/main/java/com/coredisc/presentation/dto/reportStat/ReportStatResponseDTO.java
Labels: ✨ Feature

#87 Feat: 카카오 소셜 로그인 API 구현
  build.gradle
  src/main/java/com/coredisc/application/service/auth/SocialAuthService.java
  src/main/java/com/coredisc/application/service/auth/SocialAuthServiceImpl.java
  src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
  src/main/java/com/coredisc/common/converter/MemberConverter.java
  src/main/java/com/coredisc/common/properties/SocialProperties.java
  src/main/java/com/coredisc/common/util/RandomUsernameGenerator.java
  src/main/java/com/coredisc/config/WebConfig.java
  src/main/java/com/coredisc/presentation/controller/AuthController.java
  src/main/java/com/coredisc/presentation/controllerdocs/AuthControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/auth/AuthRequestDTO.java
  src/main/java/com/coredisc/presentation/dto/auth/KakaoUserInfo.java
Labels: ✨ Feature

#90 Feat: 마이홈(본인/타사용자) 사용자 정보 조회 API 수정
  src/main/java/com/coredisc/application/service/member/MemberQueryServiceImpl.java
  src/main/java/com/coredisc/common/converter/MemberConverter.java
  src/main/java/com/coredisc/domain/post/PostRepository.java
  src/main/java/com/coredisc/infrastructure/repository/post/JpaPostRepository.java
  src/main/java/com/coredisc/infrastructure/repository/post/PostRepositoryAdaptor.java
  src/main/java/com/coredisc/presentation/controllerdocs/MemberControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/member/MemberResponseDTO.java
Labels: ✨ Feature, 🔨 Refactor

#92 Feat: 이메일 전송, 인증코드 검증 관련 API 수정
  src/main/java/com/coredisc/application/service/auth/AuthCommandService.java
  src/main/java/com/coredisc/application/service/auth/AuthCommandServiceImpl.java
  src/main/java/com/coredisc/application/service/auth/MailService.java
  src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
  src/main/java/com/coredisc/presentation/controller/AuthController.java
  src/main/java/com/coredisc/presentation/controllerdocs/AuthControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/auth/AuthRequestDTO.java
Labels: ✨ Feature, 🔨 Refactor

#99 Refactor: 카카오 로그인 API 수정
  src/main/java/com/coredisc/application/service/auth/SocialAuthServiceImpl.java
  src/main/java/com/coredisc/presentation/controllerdocs/AuthControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/auth/AuthRequestDTO.java
Labels: 🔨 Refactor

#93 Feat: 사용자 프로필 사진 변경 API 구현
  src/main/java/com/coredisc/application/service/member/MemberCommandService.java
  src/main/java/com/coredisc/application/service/member/MemberCommandServiceImpl.java
  src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
  src/main/java/com/coredisc/common/converter/ProfileImgConverter.java
  src/main/java/com/coredisc/domain/profileImg/ProfileImg.java
  src/main/java/com/coredisc/domain/profileImg/ProfileImgRepository.java
  src/main/java/com/coredisc/infrastructure/aws/s3/AmazonS3Manager.java
  src/main/java/com/coredisc/infrastructure/repository/profileImg/ProfileImgRepositoryAdaptor.java
  src/main/java/com/coredisc/presentation/controller/MemberController.java
  src/main/java/com/coredisc/presentation/controllerdocs/MemberControllerDocs.java
Labels: ✨ Feature

#95 Feat: 통계 배치 처리 구현(1)
  src/main/java/com/coredisc/CorediscApplication.java
  src/main/java/com/coredisc/application/service/disc/DiscBatchService.java
  src/main/java/com/coredisc/application/service/disc/DiscBatchServiceImpl.java
  src/main/java/com/coredisc/application/service/disc/DiscCommandService.java
  src/main/java/com/coredisc/application/service/disc/DiscCommandServiceImpl.java
  src/main/java/com/coredisc/application/service/disc/DiscQueryServiceImpl.java
  src/main/java/com/coredisc/application/service/reportStat/ReportStatBatchService.java
  src/main/java/com/coredisc/application/service/reportStat/ReportStatBatchServiceImpl.java
  src/main/java/com/coredisc/common/converter/DiscConverter.java
  src/main/java/com/coredisc/common/converter/ReportStatConverter.java
  src/main/java/com/coredisc/common/util/DateUtil.java
  src/main/java/com/coredisc/common/util/DiscCreationHelper.java
  src/main/java/com/coredisc/domain/disc/DiscRepository.java
  src/main/java/com/coredisc/domain/member/MemberRepository.java
  src/main/java/com/coredisc/domain/post/PostRepository.java
  src/main/java/com/coredisc/domain/postAnswer/PostAnswerRepository.java
  src/main/java/com/coredisc/domain/reportStats/DailyAnswerHourStat.java
  src/main/java/com/coredisc/domain/reportStats/DailyRandomQuestionStat.java
  src/main/java/com/coredisc/domain/reportStats/MonthlyFixedQuestionStat.java
  src/main/java/com/coredisc/domain/todayQuestion/TodayQuestionRepository.java
  src/main/java/com/coredisc/infrastructure/repository/answer/JpaPostAnswerRepository.java
  src/main/java/com/coredisc/infrastructure/repository/answer/PostAnswerRepositoryAdaptor.java
  src/main/java/com/coredisc/infrastructure/repository/disc/DiscRepositoryAdaptor.java
  src/main/java/com/coredisc/infrastructure/repository/disc/JpaDiscRepository.java
  src/main/java/com/coredisc/infrastructure/repository/member/JpaMemberRepository.java
  src/main/java/com/coredisc/infrastructure/repository/member/MemberRepositoryAdaptor.java
  src/main/java/com/coredisc/infrastructure/repository/post/PostRepositoryAdaptor.java
  src/main/java/com/coredisc/infrastructure/repository/post/queryDsl/QueryPostRepository.java
  src/main/java/com/coredisc/infrastructure/repository/post/queryDsl/QueryPostRepositoryImpl.java
  src/main/java/com/coredisc/infrastructure/repository/question/JpaTodayQuestionRepository.java
  src/main/java/com/coredisc/infrastructure/repository/question/TodayQuestionRepositoryAdapter.java
  src/main/java/com/coredisc/infrastructure/repository/reportStat/MonthlyFixedQuestionStatRepository.java
  src/main/java/com/coredisc/infrastructure/schedule/BatchScheduler.java
  src/test/java/com/coredisc/BatchSchedulerTest.java
Labels: ✨ Feature

#100 Feat: 디바이스 토큰 관련 API 구현
  src/main/java/com/coredisc/application/service/auth/AuthCommandService.java
  src/main/java/com/coredisc/application/service/auth/AuthCommandServiceImpl.java
  src/main/java/com/coredisc/application/service/device/DeviceCommandService.java
  src/main/java/com/coredisc/application/service/device/DeviceCommandServiceImpl.java
  src/main/java/com/coredisc/application/service/device/DeviceQueryService.java
  src/main/java/com/coredisc/application/service/device/DeviceQueryServiceImpl.java
  src/main/java/com/coredisc/application/service/member/MemberCommandServiceImpl.java
  src/main/java/com/coredisc/common/converter/DeviceConverter.java
  src/main/java/com/coredisc/domain/device/Device.java
  src/main/java/com/coredisc/domain/device/DeviceRepository.java
  src/main/java/com/coredisc/infrastructure/repository/device/DeviceRepositoryAdaptor.java
  src/main/java/com/coredisc/infrastructure/repository/device/JpaDeviceRepository.java
  src/main/java/com/coredisc/presentation/controller/AuthController.java
  src/main/java/com/coredisc/presentation/controller/DeviceController.java
  src/main/java/com/coredisc/presentation/controllerdocs/AuthControllerDocs.java
  src/main/java/com/coredisc/presentation/controllerdocs/DeviceControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/device/DeviceRequestDTO.java
  src/main/java/com/coredisc/presentation/dto/device/DeviceResponseDTO.java
Labels: ✨ Feature

#102 Feat: 저장한 공유 질문, 인기 질문 조회 API 구현
  src/main/java/com/coredisc/application/service/question/QuestionQueryService.java
  src/main/java/com/coredisc/application/service/question/QuestionQueryServiceImpl.java
  src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
  src/main/java/com/coredisc/common/converter/QuestionConverter.java
  src/main/java/com/coredisc/domain/mapping/memberOfficialQuestion/MemberOfficialQuestionRepository.java
  src/main/java/com/coredisc/domain/officialQuestion/OfficialQuestionRepository.java
  src/main/java/com/coredisc/infrastructure/repository/question/MemberOfficialQuestionRepositoryAdapter.java
  src/main/java/com/coredisc/infrastructure/repository/question/OfficialQuestionRepositoryAdapter.java
  src/main/java/com/coredisc/infrastructure/repository/question/querydsl/QueryMemberOfficialQuestionRepository.java
  src/main/java/com/coredisc/infrastructure/repository/question/querydsl/QueryMemberOfficialQuestionRepositoryImpl.java
  src/main/java/com/coredisc/infrastructure/repository/question/querydsl/QueryOfficialQuestionRepository.java
  src/main/java/com/coredisc/infrastructure/repository/question/querydsl/QueryOfficialQuestionRepositoryImpl.java
  src/main/java/com/coredisc/presentation/controller/QuestionController.java
  src/main/java/com/coredisc/presentation/controllerdocs/QuestionControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/question/QuestionResponseDTO.java
Labels: ✨ Feature

#106 Feat: 저장한 공유질문 즐겨찾기 추가/삭제 API 구현
  src/main/java/com/coredisc/application/service/question/QuestionCommandService.java
  src/main/java/com/coredisc/application/service/question/QuestionCommandServiceImpl.java
  src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
  src/main/java/com/coredisc/common/converter/QuestionConverter.java
  src/main/java/com/coredisc/domain/mapping/memberOfficialQuestion/MemberOfficialQuestion.java
  src/main/java/com/coredisc/presentation/controller/QuestionController.java
  src/main/java/com/coredisc/presentation/controllerdocs/QuestionControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/question/QuestionResponseDTO.java
Labels: ✨ Feature

#108 Feat: 선택형 일기 배치 처리 구현(2)
  src/main/java/com/coredisc/application/service/reportStat/ReportRawData.java
  src/main/java/com/coredisc/application/service/reportStat/ReportStatBatchServiceImpl.java
  src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
  src/main/java/com/coredisc/common/converter/ReportStatConverter.java
  src/main/java/com/coredisc/common/util/DailyEnumMappingHelper.java
  src/main/java/com/coredisc/domain/reportStats/DailyRandomQuestionStat.java
  src/main/java/com/coredisc/domain/reportStats/MonthlyFixedQuestionStat.java
  src/main/java/com/coredisc/domain/reportStats/MonthlySelectionDiaryStat.java
  src/main/java/com/coredisc/infrastructure/repository/reportStat/MonthlySelectionDiaryStatRepository.java
  src/main/java/com/coredisc/infrastructure/schedule/BatchScheduler.java
  src/main/java/com/coredisc/presentation/dto/reportStat/ReportStatResponseDTO.java
Labels: ✨ Feature

#110 Refactor: 공유 질문 API 로직 수정
  src/main/java/com/coredisc/common/converter/QuestionConverter.java
  src/main/java/com/coredisc/infrastructure/repository/question/querydsl/QueryMemberOfficialQuestionRepositoryImpl.java
  src/main/java/com/coredisc/presentation/dto/question/QuestionResponseDTO.java
Labels: 🔨 Refactor

#117 Refactor: 월별 리포트 조회 API 수정
  src/main/java/com/coredisc/application/service/reportStat/ReportRawData.java
  src/main/java/com/coredisc/application/service/reportStat/ReportStatBatchServiceImpl.java
  src/main/java/com/coredisc/application/service/reportStat/ReportStatQueryService.java
  src/main/java/com/coredisc/application/service/reportStat/ReportStatQueryServiceImpl.java
  src/main/java/com/coredisc/common/converter/ReportStatConverter.java
  src/main/java/com/coredisc/infrastructure/repository/reportStat/DailyRandomQuestionStatRepository.java
  src/main/java/com/coredisc/presentation/controller/ReportStatController.java
  src/main/java/com/coredisc/presentation/controllerdocs/ReportStatControllerDocs.java
  src/main/java/com/coredisc/presentation/dto/reportStat/ReportStatRequestDTO.java
  src/main/java/com/coredisc/presentation/dto/reportStat/ReportStatResponseDTO.java
Labels: 🔨 Refactor
